FROM python:latest

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ARG DATABASE_URL

ENV DATABASE_URL=${DATABASE_URL}

# Comando para iniciar o Celery
CMD ["celery", "-A", "run.celery", "worker", "--loglev  el=info"]
