FROM python:latest

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ENV FLASK_APP=run
ENV FLASK_DEBUG=1

EXPOSE 8050

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "8050"]

